### ISSUE TITLE
Clang error when building app

### ISSUE THREAD

**Issue by Jupi007** [canonical/flutter-snap#63]
When running an app with a customized `linux` folder, the build fails and returns this error:

```
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This happens for example with https://github.com/Feichtmeier/settings, which use `libhandy` to have all rounded corners.

All other "normal" apps run as expected.

### Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on Ubuntu 21.10 5.13.0-22-generic, locale fr_FR.UTF-8)
[✓] Linux toolchain - develop for Linux desktop
[✓] VS Code
[✓] Connected device (1 available)

• No issues found!
```

### Full error return
```
$ /snap/bin/flutter run
Launching lib/main.dart on Linux in debug mode...
/snap/flutter/current/usr/bin/ld: warning: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/crt1.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Building Linux application...                                           
Exception: Build process failed

```

**Comment by jpnurmi** [comment]
This is probably not related to the snap, but you can see the linker error details by running: `/snap/bin/flutter run --verbose`.

**Comment by Jupi007** [comment]
In fact, manual install of Flutter runs well.
That's why I think it is related to the snap.

Here is the most useful lines of the verbose build return:

```
[   +2 ms] /usr/lib/x86_64-linux-gnu/libhandy-1.so: undefined reference to `g_task_set_name'
[        ] //lib/x86_64-linux-gnu/libepoxy.so.0: undefined reference to `dlopen@GLIBC_2.34'
[        ] //lib/x86_64-linux-gnu/libepoxy.so.0: undefined reference to `dlerror@GLIBC_2.34'
[        ] /usr/lib/x86_64-linux-gnu/libhandy-1.so: undefined reference to `g_atomic_ref_count_init'
[        ] /usr/lib/x86_64-linux-gnu/libhandy-1.so: undefined reference to `g_atomic_ref_count_dec'
[        ] /usr/lib/x86_64-linux-gnu/libhandy-1.so: undefined reference to `g_task_get_name'
[        ] /usr/lib/x86_64-linux-gnu/libhandy-1.so: undefined reference to `log2@GLIBC_2.29'
[        ] /usr/lib/x86_64-linux-gnu/libhandy-1.so: undefined reference to `gtk_event_controller_key_new'
[        ] /usr/lib/x86_64-linux-gnu/libhandy-1.so: undefined reference to `pow@GLIBC_2.29'
[        ] //lib/x86_64-linux-gnu/libepoxy.so.0: undefined reference to `dlsym@GLIBC_2.34'
[        ] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[        ] ninja: build stopped: subcommand failed.
[  +14 ms] Building Linux application... (completed in 8,5s)
[+16036 ms] Exception: Build process failed
[   +2 ms] "flutter run" took 25 878ms.
[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:674:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

Btw @Feichtmeier also have this issue with the snap.

**Comment by jpnurmi** [comment]
You're right, it clearly has something to do with the snap. :slightly_smiling_face: I wrongly assumed there was something wrong with the recently added libhandy linking rules.

**Comment by lapisdecor** [comment]
I'm on Ubuntu Jammy by the way (do-release-upgrade -d)

**Comment by KameiKojirou** [comment]
Same issue here as lapisdecor. Pop!_OS 22.04 with Snap.

**Comment by zsmiklos** [comment]
Manuall install is a temporary solution. Not acceptable because snapcraft works with snap flutter.
The reason of the problem is that embedded cmake is outdated: with version 10.0
Why they can not refresh the environment of this Flutter engine? Because this is useless. I must use manual install of Flutter, but snapcraft can not use manually installed Flutter. So you can not publish Linux snap with Flutter at all. You can not publish app with this outdated Flutter environment. PS: Flutter is awesome but this release is useless.

**Comment by jpnurmi** [comment]
You can build snaps with Flutter from Git:
- [firmware-updater](https://github.com/canonical/firmware-updater/blob/main/snap/snapcraft.yaml#L20-L39) (core22)
- [software](https://github.com/ubuntu-flutter-community/software/blob/main/snap/snapcraft.yaml#L20-L40) (core22)
- [ubuntu-desktop-installer](https://github.com/canonical/ubuntu-desktop-installer/blob/main/snap/snapcraft.yaml#L128-L148) (core20)
- [workshops](https://github.com/canonical/workshops/blob/main/snap/snapcraft.yaml#L19-L37) (core22)

For what it's worth, there's also a new [core22-based flutter plugin](https://github.com/snapcore/snapcraft/pull/3952) in the works.

**Comment by zsmiklos** [comment]
@jpnurmi Thanks for the idea. After some hours trial the result is 
I edited the snapcraft.yaml based on the Workshops template, but it gives some different error messages.
( cmake error at /usr/share/cmake-3.22/modules/findpackagehandlestandardargs.cmake:230 (message): could not find pkgconfig (missing: pkg_config_executable)  )
(The mentioned one at Webshops does not work too, it throws an error message by running with snapcraft after downloading it)

There is a core18 version that Google refers to on the official Flutter for Linux page, but it doesn't work, it's buggy with flutter-snap.

Canonical and Google are working very, very hard on Flutter. I thank them. But why is it so hard to run and publish a Flutter app on Linux? Why they not make it easier? 

Since 2021 the flutter-sanp is buggy (can not start a Flutter app with it). Thank you in advance for the Canonical if they fix it.

**Comment by jpnurmi** [comment]
Manually installing Flutter for Linux requires a bunch of [additional dependencies](https://docs.flutter.dev/get-started/install/linux#additional-linux-requirements) including cmake, clang, ninja, gtk3-dev, and so on. Flutter-snap has its share of issues but what it essentially does is to simplify this process by bundling the tools and development headers for you. However, these are just two alternative ways of installing Flutter on your **host** for developing Flutter apps on Linux.

No matter which way you install Flutter on your host, that Flutter installation is not used when you build snaps with snapcraft. The build process runs in a separate container, for which you must declare the desired build dependencies in snapcraft.yaml.

> ( cmake error at /usr/share/cmake-3.22/modules/findpackagehandlestandardargs.cmake:230 (message): could not find pkgconfig (missing: pkg_config_executable) )

Based on the error message, I'd try:
```yaml
    build-packages:
      - pkg-config
```

**Comment by zsmiklos** [comment]
@jpnurmi Thank you for your help and for your kindness! But it does not work, an error message appears:

```
[  +31 ms] -- Checking for module 'gstreamer-1.0'
[   +1 ms] --   No package 'gstreamer-1.0' found
[        ] CMake Error at /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:603 (message):
[   +1 ms]   A required package was not found
[        ] Call Stack (most recent call first):
[        ]   /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:825 (_pkg_check_modules_internal)
```
Can you send me a link where I can find a very simple snapcraft.yaml for a very simple Flutter project that works? Which works.

This is my wrong snapcraft.yaml (I don't know if this is an off-topic or not, but this problem comes because of original problem. My file is):

```
name: my-app
version: 1.0.0
summary: My App
description: test

confinement: devmode # use 'strict' once you have the right plugs and slots
#confinement: strict
base: core22
#grade: stable
grade: devel

#slots:
#  dbus-my-app: # adjust accordingly to your app name
#    interface: dbus
#    bus: session
#    name: com.myapp # adjust accordingly to your app name and

apps:
  my-app:
    command: myapp_flutter
    #extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
#    extensions: [gnome]
    plugs:
#      - lxd
      - network
#    slots:
#      - dbus-my-app

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-branch: stable
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
    build-packages:
      - clang
      - cmake
      #- curl
      - ninja-build
      - unzip
      #- xz-utils
      #- zip
      - pkg-config  # added because of a github hint
      - libgtk-3-dev
      - liblzma-dev
      #- libgstreamer1.0-dev
      #- libgstreamer-plugins-base1.0-dev
      #- gstreamer1.0*
      #- libgstreamer1.0-0
      #- gstreamer1.0-plugins-base
      #- gstreamer1.0-plugins-good
      #- gstreamer1.0-plugins-bad
      #- gstreamer1.0-plugins-ugly
      #- gstreamer1.0-libav
      #- gstreamer1.0-doc
      #- gstreamer1.0-tools
#    prime:
#      - -*

  my-app:
    after: [ flutter-git ]
    source: .
    plugin: nil
    override-build: |
      set -eux
      flutter doctor
      flutter pub get
      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/
      

```

**Comment by jpnurmi** [comment]
@zsmiklos I think you're on the right track even though this is indeed not related to flutter-snap. You'll find the best snapcraft experts on the forums: https://forum.snapcraft.io/.

> ```
> [  +31 ms] -- Checking for module 'gstreamer-1.0'
> [   +1 ms] --   No package 'gstreamer-1.0' found
> ```

The error indicates that your Flutter app uses GStreamer. A basic Flutter hello world example won't help with GStreamer packaging issues. I'm guessing your app wants to play audio and therefore uses an audio plugin of some sort. I'm no snapcraft expert but I'd try something like this:

```yaml
  my-app:
    ...
    build-packages:
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
    stage-packages:
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0
    ...

apps:
  my-app:
    ...
    plugs:
      - audio-playback
```
